### ISSUE TITLE
What is "owned"?

### ISSUE THREAD

**Issue by taoeffect** [ethereum/dapp-bin#39]
I can't seem to find a definition for it, yet many contracts seem to subclass from it.

Also, what is `#require`? Can't find documentation for that construct (did the syntax change?).

**Comment by taoeffect** [comment]
I see `contract owned` is defined in a commented out section. Odd. No clue still though about `#require`.

**Comment by chriseth** [comment]
`#require` was replaced by `import`. owned is defined here:
https://github.com/ethereum/solidity/blob/develop/libsolidity/CompilerStack.cpp#L52
This is a very crude way to provide a standard library which is still under development.

**Comment by pml10628** [comment]
Realbank(RBT)-1ede817398a84d4c8533f423444681cf
