### ISSUE TITLE
[Wallet.sol] daily limit will not get reset daily

### ISSUE THREAD

**Issue by colm** [ethereum/dapp-bin#64]
I think the [`underLimit`](https://github.com/ethereum/dapp-bin/blob/master/wallet/wallet.sol#L254) function is broken. It compares `today() > m_lastDay`. Where `today() = now / 1 days`, `1 days = 86400` seconds and `m_lastDay = now`. `today()` will be 86400 times smaller than `m_lastDay` due to the division.

The intention is that `today() > m_lastDay` will be true when 86401 seconds have elapsed which is `today() + 86402 `. But the implementation means it will only be true when `today() * 86400 + 1`

**Comment by bencxr** [comment]
where are you seeing m_lastDay = now? is it not m_lastDay = today() ?

**Comment by colm** [comment]
Yes, you are correct. I can't remember if i made a mistake reading it before or what. But yes this is not an issue :-/
